; Included by the NSIS installer script
; Don't forget to also change ProductInfo.h!

!define PRODUCT_NAME "StepMania"
!define PRODUCT_VER "3.9 random build"
; !define PRODUCT_VER "3.9 rc3"
!define PRODUCT_NAME_VER "${PRODUCT_NAME} ${PRODUCT_VER}"

; String used for the install directory and registry locations
; Official releases = "StepMania"; intermediate releases = "StepMania CVS".
!define PRODUCT_ID "StepMania"
