#ifndef STEPS_H
#define STEPS_H
/*
-----------------------------------------------------------------------------
 Class: Steps

 Desc: Holds note information for a Song.  A Song may have one or more Notess.
	A Steps can be played by one or more Styles.  See StyleDef.h for more info on
	Styles.

 Copyright (c) 2001-2002 by the person(s) listed below.  All rights reserved.
	Chris Danford
-----------------------------------------------------------------------------
*/

#include "GameConstantsAndTypes.h"
#include "PlayerNumber.h"
#include "Grade.h"
class NoteData;
class Profile;

class Steps
{
public:
	Steps();
	~Steps();

	// initializers
	void AutogenFrom( const Steps *parent, StepsType ntTo );
	void CopyFrom( Steps* pSource, StepsType ntTo );
	void CreateBlank( StepsType ntTo );

	void Compress() const;
	void Decompress() const;
	void DeAutogen();	/* If this Steps is autogenerated, make it a real Steps. */

	// Use a special value of difficulty
	bool IsAnEdit() const { return m_Difficulty == DIFFICULTY_EDIT; }
	bool WasLoadedFromProfile() const { return m_LoadedFromProfile != PROFILE_SLOT_INVALID; }
	CString GetDescription() const { return Real()->m_sDescription; }
	Difficulty GetDifficulty() const { return Real()->m_Difficulty; }
	CString GetID() const /* used for Song::GetStepsByID */
	{
		Difficulty dc = GetDifficulty();
		ASSERT( dc != DIFFICULTY_INVALID );

		if( dc == DIFFICULTY_EDIT )
			return GetDescription();
		else
			return DifficultyToString(dc);
	}
	int GetMeter() const { return Real()->m_iMeter; }
	const RadarValues& GetRadarValues() const { return Real()->m_RadarValues; }

	void SetDescription(CString desc);
	void SetDifficulty(Difficulty d);
	void SetLoadedFromProfile( ProfileSlot slot ) { m_LoadedFromProfile = slot; }
	void SetMeter(int meter);
	void SetRadarValue(int r, float val);
	bool IsAutogen() const;	// Was created by autogen?
	float PredictMeter() const;
	
	StepsType	m_StepsType;

	void		GetNoteData( NoteData* pNoteDataOut ) const;
	void		SetNoteData( const NoteData* pNewNoteData );
	void		SetSMNoteData( const CString &notes_comp, const CString &attacks_comp );
	void		GetSMNoteData( CString &notes_comp_out, CString &attacks_comp_out ) const;

	void TidyUpData();

protected:
	/* If this Steps is autogenerated, this will point to the autogen
	 * source.  If this is true, notes_comp will always be NULL. */
	const Steps *parent;

	/* We can have one or both of these; if we have both, they're always identical.
	 * Call Compress() to force us to only have notes_comp; otherwise, creation of 
	 * these is transparent. */
	mutable NoteData *notes;
	struct CompressedNoteData
	{
		CString notes, attacks;
	};
	mutable CompressedNoteData *notes_comp;

	const Steps *Real() const;

	/* These values are pulled from the autogen source first, if there is one. */
	ProfileSlot		m_LoadedFromProfile;	// PROFILE_SLOT_INVALID if wasn't loaded from a profile
	CString			m_sDescription;		// Step author, edit name, or something meaningful
	Difficulty		m_Difficulty;		// difficulty classification
	int				m_iMeter;			// difficulty rating from MIN_METER to MAX_METER
	RadarValues		m_RadarValues;
};

#endif
