#ifndef STYLE_H
#define STYLE_H

enum Style
{
	STYLE_DANCE_SINGLE,
	STYLE_DANCE_VERSUS,
	STYLE_DANCE_DOUBLE,
	STYLE_DANCE_COUPLE,
	STYLE_DANCE_SOLO,
	STYLE_DANCE_EDIT_COUPLE,
	STYLE_PUMP_SINGLE,
	STYLE_PUMP_VERSUS,
	STYLE_PUMP_HALFDOUBLE,
	STYLE_PUMP_DOUBLE,
	STYLE_PUMP_COUPLE,
	STYLE_PUMP_EDIT_COUPLE,
	STYLE_EZ2_SINGLE,
	STYLE_EZ2_REAL,
	STYLE_EZ2_SINGLE_VERSUS,
	STYLE_EZ2_REAL_VERSUS,
	STYLE_EZ2_DOUBLE,
	STYLE_PARA_SINGLE,
	STYLE_DS3DDX_SINGLE,
	STYLE_BM_SINGLE,
	STYLE_BM_DOUBLE,
	STYLE_IIDX_SINGLE7,
	STYLE_IIDX_DOUBLE7,
	STYLE_IIDX_SINGLE5,
	STYLE_IIDX_DOUBLE5,
	STYLE_IIDX_EDIT_SINGLE5,
	STYLE_IIDX_EDIT_DOUBLE5,
	STYLE_MANIAX_SINGLE,
	STYLE_MANIAX_VERSUS,
	STYLE_MANIAX_DOUBLE,
	STYLE_TECHNO_SINGLE8,
	STYLE_TECHNO_VERSUS8,
	STYLE_PNM_FIVE,
	STYLE_PNM_NINE,
	STYLE_LIGHTS_CABINET,
	NUM_STYLES,	// leave this at the end
	STYLE_INVALID,
};

#endif

/*
 * (c) 2001-2002 Chris Danford
 * All rights reserved.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, and/or sell copies of the Software, and to permit persons to
 * whom the Software is furnished to do so, provided that the above
 * copyright notice(s) and this permission notice appear in all copies of
 * the Software and that both the above copyright notice(s) and this
 * permission notice appear in supporting documentation.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS
 * INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT
 * OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
 * OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */
