list(APPEND SMDATA_OS_SRC
	"archutils/Win32/AppInstance.cpp"
	"archutils/Win32/arch_setup.cpp"
	"archutils/Win32/arch_time.cpp"
	"archutils/Win32/CommandLine.cpp"
	"archutils/Win32/Crash.cpp"
	"archutils/Win32/CrashHandlerChild.cpp"
	"archutils/Win32/CrashHandlerNetworking.cpp"
	"archutils/Win32/DebugInfoHunt.cpp"
	"archutils/Win32/DialogUtil.cpp"
	"archutils/Win32/DirectXHelpers.cpp"
	"archutils/Win32/ErrorStrings.cpp"
	"archutils/Win32/GetFileInformation.cpp"
	"archutils/Win32/GotoURL.cpp"
	"archutils/Win32/GraphicsWindow.cpp"
	"archutils/Win32/MessageWindow.cpp"
	"archutils/Win32/RegistryAccess.cpp"
	"archutils/Win32/RestartProgram.cpp"
	"archutils/Win32/SpecialDirs.cpp"
	"archutils/Win32/USB.cpp"
	"archutils/Win32/VideoDriverInfo.cpp"
	"archutils/Win32/WindowIcon.cpp"
	"archutils/Win32/WindowsDialogBox.cpp"
	"archutils/Win32/WindowsResources.rc"
)

list(APPEND SMDATA_OS_HPP
	"archutils/Win32/AppInstance.h"
	"archutils/Win32/arch_setup.h"
	"archutils/Win32/CommandLine.h"
	"archutils/Win32/Crash.h"
	"archutils/Win32/CrashHandlerInternal.h"
	"archutils/Win32/CrashHandlerNetworking.h"
	"archutils/Win32/DebugInfoHunt.h"
	"archutils/Win32/DialogUtil.h"
	"archutils/Win32/DirectXHelpers.h"
	"archutils/Win32/ErrorStrings.h"
	"archutils/Win32/GetFileInformation.h"
	"archutils/Win32/GotoURL.h"
	"archutils/Win32/GraphicsWindow.h"
	"archutils/Win32/MessageWindow.h"
	"archutils/Win32/RegistryAccess.h"
	"archutils/Win32/RestartProgram.h"
	"archutils/Win32/SpecialDirs.h"
	"archutils/Win32/USB.h"
	"archutils/Win32/VideoDriverInfo.h"
	"archutils/Win32/WindowIcon.h"
	"archutils/Win32/WindowsDialogBox.h"
	"archutils/Win32/WindowsResources.h"
)

source_group("OS Specific" FILES ${SMDATA_OS_SRC} ${SMDATA_OS_HPP})