# Inspired by Jeremy Tregunna's cmake work <jeremy.tregunna@me.com>
#
# Find libvorbisfile.

FIND_PATH(VORBISFILE_INCLUDE_DIR vorbis/vorbisfile.h)

SET(VORBISFILE_NAMES ${VORBISFILE_NAMES} vorbisfile libvorbisfile)
FIND_LIBRARY(VORBISFILE_LIBRARY NAMES ${VORBISFILE_NAMES} PATH)

IF(VORBISFILE_INCLUDE_DIR AND VORBISFILE_LIBRARY)
	SET(VORBISFILE_FOUND TRUE)
ENDIF(VORBISFILE_INCLUDE_DIR AND VORBISFILE_LIBRARY)

IF(VORBISFILE_FOUND)
	IF(NOT VorbisFile_FIND_QUIETLY)
		MESSAGE(STATUS "Found VorbisFile: ${VORBISFILE_LIBRARY}")
	ENDIF (NOT VorbisFile_FIND_QUIETLY)
ELSE(VORBISFILE_FOUND)
	IF(VorbisFile_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find vorbisfile")
	ENDIF(VorbisFile_FIND_REQUIRED)
ENDIF (VORBISFILE_FOUND)

